databases:
  - name: asopadel_db
    databaseName: asopadel_barinas
    user: asopadel_user

services:
  - type: web
    name: asopadel_web
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn asopadel_barinas.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: asopadel_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*" 
